[package]
name = "wave-steganography"
version = "0.1.0"
authors = ["austin-millan <austin.millan@protonmail.com>"]

[dependencies]
hound = "*"
derive_builder = "*"
# dwt = "0.5.2"

[workspace]
members = ["src/chaos_image_encryption"]

[dependencies.chaos_image_encryption]
path = "src/chaos_image_encryption"