[package]
name = "wave-steganography"
version = "0.1.0"
authors = ["austin-millan <austin.millan@protonmail.com>"]

[workspace]
path = "src/scramble_image"

[dependencies.scramble_image]
path = "src/scramble_image"

[dependencies]
dwt = "0.5.2"
image = "*"
rand = "*"