[package]
name = "scramble_image"
version = "0.1.0"
authors = ["austin-millan <austin.millan@protonmail.com>"]

[dependencies]
image = "*"
imageproc = "*"
derive_builder = "*"

[lib]
name = "scramble_image"
path = "src/lib.rs"